name: First CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build using gcc
        run: gcc -Wall -Werror main.c -o program
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: program
          path: program